export enum EApiFunctionTransactionFailureStage {
	AFTER_COMMIT = "AFTER_COMMIT",
	AFTER_ERROR_COMMIT = "AFTER_ERROR_COMMIT",
	AFTER_ERROR_ROLLBACK = "AFTER_ERROR_ROLLBACK",
	AFTER_ROLLBACK = "AFTER_ROLLBACK",
	BEFORE_ERROR_COMMIT = "BEFORE_ERROR_COMMIT",
	BEFORE_ERROR_ROLLBACK = "BEFORE_ERROR_ROLLBACK",
	COMMIT = "COMMIT",
	ROLLBACK = "ROLLBACK",
}
