export enum EApiPropertyDataType {
	BOOLEAN = "boolean",
	DATE = "date",
	DATE_TIME = "date-time",
	DOUBLE = "double",
	EMAIL = "email",
	INTEGER = "integer",
	IP = "ip",
	LOWERCASE_STRING = "lowercase-string",
	NUMBER = "number",
	REGEXP = "regexp",
	STRING = "string",
	TEXT = "text",
	TIME = "time",
	UPPERCASE_STRING = "uppercase-string",
	URL = "url",
	UUID = "uuid",
}
