const RESERVED_METHOD_PREFIX: string = "";
const OBSERVABLE_METADATA_KEY: string = "API_CONTROLLER_OBSERVABLE_METADATA_KEY";

export const CONTROLLER_API_DECORATOR_CONSTANT: {
	readonly OBSERVABLE_METADATA_KEY: string;
	readonly RESERVED_METHOD_PREFIX: string;
} = {
	OBSERVABLE_METADATA_KEY,
	RESERVED_METHOD_PREFIX,
} as const;
