const RESERVED_METHOD_PREFIX: string = "";
const OBSERVABLE_METADATA_KEY: string = "API_CONTROLLER_OBSERVABLE_METADATA_KEY";
const SECURABLE_METADATA_KEY: string = "API_CONTROLLER_SECURABLE_METADATA_KEY";
const ENTITY_METADATA_KEY: string = "API_CONTROLLER_ENTITY_METADATA_KEY";

export const CONTROLLER_API_DECORATOR_CONSTANT: {
	readonly ENTITY_METADATA_KEY: string;
	readonly OBSERVABLE_METADATA_KEY: string;
	readonly RESERVED_METHOD_PREFIX: string;
	readonly SECURABLE_METADATA_KEY: string;
} = {
	ENTITY_METADATA_KEY,
	OBSERVABLE_METADATA_KEY,
	RESERVED_METHOD_PREFIX,
	SECURABLE_METADATA_KEY,
} as const;
