const ROUTE_METADATA_KEY: string = "API_METHOD_ROUTE_METADATA_KEY";
const ROUTE_RUNTIME_PROPERTIES_METADATA_KEY: string = "API_METHOD_ROUTE_RUNTIME_PROPERTIES_METADATA_KEY";

export const METHOD_API_DECORATOR_CONSTANT: {
	readonly ROUTE_METADATA_KEY: string;
	readonly ROUTE_RUNTIME_PROPERTIES_METADATA_KEY: string;
} = {
	ROUTE_METADATA_KEY,
	ROUTE_RUNTIME_PROPERTIES_METADATA_KEY,
} as const;
