const ACTION_METADATA_KEY: string = "API_METHOD_ACTION_METADATA_KEY";
const AUTHORIZATION_METADATA_KEY: string = "API_METHOD_AUTHORIZATION_METADATA_KEY";
const ROUTE_TYPE_METADATA_KEY: string = "API_METHOD_ROUTE_TYPE_METADATA_KEY";

export const METHOD_API_DECORATOR_CONSTANT: {
	readonly ACTION_METADATA_KEY: string;
	readonly AUTHORIZATION_METADATA_KEY: string;
	readonly ROUTE_TYPE_METADATA_KEY: string;
} = {
	ACTION_METADATA_KEY,
	AUTHORIZATION_METADATA_KEY,
	ROUTE_TYPE_METADATA_KEY,
} as const;
