const METADATA_PROPERTY_NAME: string = "API_PROPERTY_DESCRIBE";

export const PROPERTY_DESCRIBE_DECORATOR_API_CONSTANT: { readonly METADATA_PROPERTY_NAME: string } = {
	METADATA_PROPERTY_NAME,
} as const;
