const OBSERVABLE_METADATA_KEY: string = "API_SERVICE_OBSERVABLE_METADATA_KEY";

export const SERVICE_API_DECORATOR_CONSTANT: {
	readonly OBSERVABLE_METADATA_KEY: string;
} = {
	OBSERVABLE_METADATA_KEY,
} as const;
