const FUNCTION_METADATA_KEY: string = "API_SUBSCRIBER_FUNCTION_METADATA_KEY";
const ROUTE_METADATA_KEY: string = "API_SUBSCRIBER_ROUTE_METADATA_KEY";

export const SUBSCRIBER_API_DECORATOR_CONSTANT: {
	readonly FUNCTION_METADATA_KEY: string;
	readonly ROUTE_METADATA_KEY: string;
} = {
	FUNCTION_METADATA_KEY,
	ROUTE_METADATA_KEY,
} as const;
