const POLICY_METADATA_KEY: string = "API_AUTHORIZATION_POLICY_METADATA_KEY";
const DEFAULT_POLICY_ID_SUFFIX: string = ".authorization.policy";

export const AUTHORIZATION_POLICY_DECORATOR_CONSTANT: {
	readonly DEFAULT_POLICY_ID_SUFFIX: string;
	readonly METADATA_KEY: string;
} = {
	DEFAULT_POLICY_ID_SUFFIX,
	METADATA_KEY: POLICY_METADATA_KEY,
} as const;
