const MINIMUM_ERROR_LENGTH: number = 3;
const MAXIMUM_ERROR_LENGTH: number = 64;
const MINIMUM_ERROR_MESSAGE_LENGTH: number = 3;
const MAXIMUM_ERROR_MESSAGE_LENGTH: number = 64;

export const EXCEPTION_DTO_CONSTANT: {
	readonly MAXIMUM_ERROR_LENGTH: number;
	readonly MAXIMUM_ERROR_MESSAGE_LENGTH: number;
	readonly MINIMUM_ERROR_LENGTH: number;
	readonly MINIMUM_ERROR_MESSAGE_LENGTH: number;
} = {
	MAXIMUM_ERROR_LENGTH,
	MAXIMUM_ERROR_MESSAGE_LENGTH,
	MINIMUM_ERROR_LENGTH,
	MINIMUM_ERROR_MESSAGE_LENGTH,
} as const;
