const MAXIMUM_MEASUREMENTS: number = 256;
const MAXIMUM_METHOD_NAME_LENGTH: number = 256;
const MAXIMUM_SELECTORS: number = 32;

export const API_FUNCTION_TRANSACTION_OBSERVATION_CONSTANT: {
	readonly MAXIMUM_MEASUREMENTS: number;
	readonly MAXIMUM_METHOD_NAME_LENGTH: number;
	readonly MAXIMUM_SELECTORS: number;
} = {
	MAXIMUM_MEASUREMENTS,
	MAXIMUM_METHOD_NAME_LENGTH,
	MAXIMUM_SELECTORS,
} as const;
