export type * from "./create-properties.type";
export type * from "./delete-criteria.type";
export type * from "./get-list-properties-where.type";
export type * from "./get-list-properties.type";
export type * from "./get-many.properties";
export type * from "./get-properties.type";
export type * from "./properties.type";
export type * from "./update-criteria.type";
export type * from "./update-properties.type";
