export * from "./get-properties.type";
export * from "./create-properties.type";
export * from "./get-list-properties.type";
export * from "./update-properties.type";
export * from "./delete-criteria.type";
export * from "./update-criteria.type";
export * from "./get-many.properties";
export * from "./properties.type";
export * from "./get-list-properties-where.type";
