const DECISION_REQUEST_KEY: string = "API_AUTHORIZATION_DECISION";

export const AUTHORIZATION_DECISION_METADATA_CONSTANT: {
	readonly REQUEST_KEY: string;
} = {
	REQUEST_KEY: DECISION_REQUEST_KEY,
} as const;
