import type { TApiPropertyDescribeDtoBodyProperties, TApiPropertyDescribeDtoQueryProperties, TApiPropertyDescribeDtoRequestProperties, TApiPropertyDescribeDtoResponseProperties } from "../dto";

export type TApiPropertyDescribePropertiesBaseDtoProperties = Partial<TApiPropertyDescribeDtoBodyProperties> & Partial<TApiPropertyDescribeDtoQueryProperties> & Partial<TApiPropertyDescribeDtoRequestProperties> & Partial<TApiPropertyDescribeDtoResponseProperties>;
