const MAXIMUM_FILTER_PROPERTIES: number = 100;
const MINIMUM_FILTER_PROPERTIES: number = 2;

export const DTO_GENERATE_CONSTANT: { MAXIMUM_FILTER_PROPERTIES: number; MINIMUM_FILTER_PROPERTIES: number } = {
	MAXIMUM_FILTER_PROPERTIES,
	MINIMUM_FILTER_PROPERTIES,
} as const;
